version: '3'
services:
  backend:
    build:
      context: ./r_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # Add environment variables here
    environment:
      - DEBUG=False
    # Add database configuration if needed

  frontend:
    build:
      context: ./r_client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Add environment variables here
    environment:
      - REACT_APP_API_URL=http://backend:8000
