version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: relationship_manager_server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

  frontend:
    build:
      context: .
      dockerfile: relationship_manager_client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
