# Use the official Python image as the base image
FROM python:3.x

# Set environment variables (adjust as needed)
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE relationship_manager.settings

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . /app/
WORKDIR /app

# Run the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
