# Use the official Python image as the base image
FROM python:3.8

# Set environment variables (adjust as needed)
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE relationship_manager_server.settings

# Create and set the working directory
WORKDIR /app

# Install dependencies
COPY relationship_manager_server/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY relationship_manager_server/ /app/

# Run the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
