# Generated by Django 4.2.4 on 2023-09-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relationship_manager", "0002_alter_relationship_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationship",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
