# Generated by Django 4.2.4 on 2023-09-03 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("relationship_manager", "0003_alter_relationship_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
