# Use the official Node.js image as the base image
FROM node:14

# Set the working directory
WORKDIR /app

# Install dependencies
COPY relationship_manager_client/package.json relationship_manager_client/package-lock.json /app/
RUN npm install

# Copy the application code into the container
COPY relationship_manager_client/ /app/

# Run the React application
CMD ["npm", "start"]
