# Use the official Node.js image as the base image
FROM node:xx

# Set environment variables
ENV NODE_ENV production

# Install dependencies
COPY package*.json /app/
RUN npm install

# Copy the application code into the container
COPY . /app/
WORKDIR /app

# Build the React app
RUN npm run build

# Serve the built app using a web server
CMD ["npm", "start"]
